# Paths
collections: null
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Site settings
title: Reproducibility Breakdown
description: > # this means to ignore newlines until "baseurl:"
  A collection of documentation for OCCAM's metadata specification and basic
  operation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.occamportal.org" # the base hostname & protocol for your site

# Build settings
markdown: CustomRedcarpet

port: 8003
host: 0.0.0.0
